ALTER TABLE resume_skills ALTER COLUMN id SET NOT NULL;
ALTER TABLE skills ALTER COLUMN id SET NOT NULL;
ALTER TABLE resume_skills ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE skills ALTER COLUMN user_id SET NOT NULL;